CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	verified BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS password_tokens (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	token VARCHAR(64) NOT NULL,
	expires_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS verify_tokens (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	token VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS email_tokens (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	new_email VARCHAR(255) NOT NULL UNIQUE,
	token VARCHAR(64) NOT NULL
);

-- DELETE FROM password_resets WHERE expires_at < NOW();